
[driver]
dir = [
"/root/helm_sedna/src/flowunit",
]

[flow]
desc = "helm detection for video streams"
skip-default = false

[graph]
graphconf = """
digraph graph_helm_sedna {
\tnode [shape=Mrecord]
    video_input0 [ type=flowunit flowunit=video_input device=cpu deviceid="0" source_url="/root/helm_sedna/src/video/video.mp4" ]
    video_demuxer1 [ type=flowunit flowunit=video_demuxer device=cpu deviceid="0" ]
    video_decoder2 [ type=flowunit flowunit=video_decoder device=cpu deviceid="0" pix_fmt=rgb ]
    resize3 [ type=flowunit flowunit=resize device=cpu deviceid="0" image_height="352" image_width="640" interpolation=inter_linear ]
    packed_planar_transpose4 [ type=flowunit flowunit=packed_planar_transpose device=cpu deviceid="0" ]
    normalize5 [ type=flowunit flowunit=normalize device=cpu deviceid="0" standard_deviation_inverse="0.003921568627451,0.003921568627451,0.003921568627451" ]
    helm_infer6 [ type=flowunit flowunit=helm_infer device=cpu deviceid="0"]
    yolo3_post [type=flowunit, flowunit=yolo3_post, device=cpu, deviceid="0" ]
    videoencoder [type=flowunit, flowunit=video_encoder, device=cpu, deviceid="0", encoder=mpeg4, format=mp4, default_dest_url="/root/helm_sedna/tmp/video_tmp.mp4"]
    image_shape [type=flowunit, flowunit=image_shape, device=cpu, deviceid="0"]

    video_input0:"out_video_url" -> video_demuxer1:"in_video_url"
    video_demuxer1:"out_video_packet" -> video_decoder2:"in_video_packet"
    video_decoder2:"out_video_frame" -> resize3:"in_image"
    resize3:"out_image" -> packed_planar_transpose4:"in_image"
    packed_planar_transpose4:"out_image" -> normalize5:"in_data"
    normalize5:"out_data" -> image_shape:"input1"
    normalize5:"out_data" -> helm_infer6:"images"
    image_shape:"output1" -> helm_infer6:"shapes"
    video_decoder2:"out_video_frame" -> yolo3_post:"in_image"
    helm_infer6:"output/classes" -> yolo3_post:"in_classes"
    helm_infer6:"output/scores" -> yolo3_post:"in_scores"
    helm_infer6:"output/boxes" -> yolo3_post:"in_boxes"
    yolo3_post:"out_image" -> videoencoder:"in_video_frame"
    

}
\
"""
format = "graphviz"

[profile]
trace = false
session = false
dir = "/tmp/modelbox/perf/"
profile = false

