[base]
name = "image_shape" # The FlowUnit name 
device = "cpu" # The device the flowunit runs on,cpu,cuda,ascend
version = "1.0.0" # The version of the flowunit
description = "A flowunit for modelbox" # The description of the flowunit
group_type = "generic" # flowunit group attribution 
entry = "image_shape@Image_shapeFlowUnit" # Python flowunit entry function
type = "python" # Fixed value

# Input ports description
[input]
[input.input1]
name = "input1"
device = "cpu"
type = "float"


# Output ports description
[output]
[output.output1]
name = "output1"
type = "int"

