[base]
name = "helm_infer" # The FlowUnit name 
device = "cpu" # The device the flowunit runs on,cpu,cuda,ascend
version = "1.0.0" # The version of the flowunit
description = "A flowunit for modelbox" # The description of the flowunit
group_type = "inference" # flowunit group attribution 
stream = true # flowunit type
type = "inference" # Fixed value
entry = "./saved_model.pb" # model file path
virtual_type = "tensorflow" # inference engine type: 'tensorflow', 'tensorrt', 'torch', 'acl', 'mindspore' 

# Input ports description
[input]
[input.input1]
device = "cpu"
name = "images"
type = "float"

[input.input2]
device = "cpu"
name = "shapes"
type = "int"

# Output ports description
[output]
[output.output1]
name = "output/classes"
type = "float"

[output.output2]
name = "output/scores"
type = "float"

[output.output3]
name = "output/boxes"
type = "float"


